//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Gender { get; set; }
        public string Pincode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public byte[] Photo { get; set; }
        public byte[] C10_marksheet { get; set; }
        public byte[] C12_marksheet { get; set; }
    }
}
