//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// model used for storing details of students
    /// </summary>
    public partial class Stu_Info
    {
        
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter the name of student")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter the age of student")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Please enter the country")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Please enter the state")]
        public string State { get; set; }
        [Required(ErrorMessage = "Please specify the gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please enter the pincode")]
        public string Pincode { get; set; }
        [Required]
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
